# Generated by Django 5.2.4 on 2025-07-19 07:31

import App1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportid', models.CharField(default=App1.models.generateid, editable=False, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('Ragging', 'Ragging'), ('Harassment', 'Harassment'), ('Mental Health', 'Mental Health'), ('Discrimination', 'Discrimination'), ('Academic Misconduct', 'Academic Misconduct'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('isresolved', models.BooleanField(default=False)),
            ],
        ),
    ]
