# Generated by Django 5.2.4 on 2025-07-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('Ragging', 'Ragging'), ('Discrimination', 'Discrimination'), ('Mental Health', 'Mental Health'), ('Harassment', 'Harassment'), ('Academic Misconduct', 'Academic Misconduct'), ('Other', 'Other')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faculty_images/')),
            ],
        ),
    ]
